### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by benjamyn1993**

### CODE REVIEW

**Comment by benjamyn1993** [comment]
f

**Review by benjamyn1993 — COMMENTED** [review]
delete

**Review by benjamyn1993 — COMMENTED** [review]
Hi @sighingnow, 
Could you please delete this closed commit (I've accidentally included personal content I would like to remove). 

Thank you

**Comment by sighingnow** [comment]
I cannot do that, too. Please try contacting support@github.com.

See also: https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

**Pull request closed without merging**
